default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        # language_version inherited from default_language_version

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        # optional: add plugins
        # additional_dependencies: ["flake8-bugbear==24.8.19"]
